import type { Priority, Role } from "@/types/enums";

/** User-facing English copy. Server Action errors stay English (tests + no role leakage). */

export const copy = {
  common: {
    save: "Save",
    saving: "Saving…",
    create: "Create",
    creating: "Creating…",
    delete: "Delete",
    name: "Name",
    description: "Description",
    email: "Email",
    password: "Password",
    loading: "Loading…",
    tryAgain: "Try again",
    somethingWentWrong: "Something went wrong",
    edit: "Edit",
    remove: "Remove",
    close: "Close",
  },
  nav: {
    projects: "Projects",
    members: "Members",
    billing: "Billing",
    account: "Account",
    signOut: "Sign out",
    createOrg: "Create organization",
    expandSidebar: "Expand sidebar",
    collapseSidebar: "Collapse sidebar",
    openNav: "Open navigation",
    navigation: "Navigation",
    orgNav: "Organization navigation",
  },
  auth: {
    signIn: "Sign in",
    signingIn: "Signing in…",
    welcomeBack: "Welcome back to SYZX",
    noAccount: "Don't have an account?",
    register: "Register",
    createAccount: "Create account",
    join: "Join SYZX",
    yourName: "Your name",
    passwordMin: "Password (min. 8 characters)",
    orgName: "Organization name",
    alreadyHaveAccount: "Already have an account?",
    registering: "Creating…",
  },
  home: {
    tagline: "Multi-tenant project management for your team.",
    signIn: "Sign in",
  },
  board: {
    defaultName: "Main",
    rename: "Rename",
    boardName: "Board name",
    newColumn: "New column",
    columnName: "Column name",
    addColumn: "Add column",
    addFirstColumn: "Add first column",
    noColumns: "No columns yet",
    noColumnsHint:
      "Add your first column to start organizing cards on this board.",
    noMatchingCards: "No matching cards",
    noMatchingHint: "Change or clear your filters to see more results.",
    addCard: "Add card",
    editCard: "Edit card",
    newCard: "New card",
    title: "Title",
    dueDate: "Due date",
    priority: "Priority",
    assignee: "Assignee",
    unassigned: "Unassigned",
    labels: "Labels (comma-separated)",
    labelsPlaceholder: "bug, frontend",
    deleteColumnConfirm: "Delete this column and all of its cards?",
    deleteCardConfirm: "Delete this card?",
    dragColumn: "Drag column",
    dragCard: "Drag card",
    deleteColumn: "Delete column",
  },
  filters: {
    region: "Card search and filters",
    search: "Search cards…",
    searchAria: "Search",
    anyone: "Anyone",
    anyPriority: "Any priority",
    label: "Label",
    due: "Due",
    dueRange: "Due date range",
    dueFrom: "Due from",
    dueTo: "Due to",
    clearAll: "Clear all",
    filtering: "Filtering…",
    assignee: "Assignee",
    removeChip: "Remove",
  },
  activity: {
    button: "Activity",
    feed: "Activity feed",
    recent: "Recent activity",
    refresh: "Refresh",
    loading: "Loading activity…",
    empty: "No activity yet.",
    system: "System",
  },
  projects: {
    yourProjects: "Your projects",
    role: "role",
    newProject: "New project",
    createProject: "Create project",
    editProject: "Edit project",
    noProjects: "No projects yet",
    noProjectsHint:
      "Create your first project to get a board and start organizing work.",
    askAdmin: "Ask an admin to create a project.",
    deleteConfirm: "Delete this project with all boards, columns, and cards?",
    newBoard: "New board",
    noBoards: "No boards yet",
    noBoardsHint: "Create a board to start organizing columns and cards.",
    askAdminBoard: "Ask an admin to create a board.",
    edit: "Edit",
  },
  members: {
    title: "Members & settings",
    organization: "Organization",
    orgName: "Organization name",
    renameHint:
      "Renaming does not change the URL slug. The slug cannot be changed after creation.",
    invite: "Invite member",
    inviteHint:
      "We'll email a link if delivery is configured. You can always copy the link.",
    createInvite: "Create invitation",
    creatingInvite: "Creating…",
    copyLink: "Copy link",
    copied: "Copied",
    members: "Members",
    you: "you",
    joined: "Joined",
    remove: "Remove",
    removeConfirm: "Remove this member from the organization?",
    pending: "Pending invitations",
    pendingHint:
      "Unused invitations expire after 7 days. Revoking invalidates the link.",
    noPending: "No pending invitations.",
    revoke: "Revoke",
    leave: "Leave organization",
    leaveHint:
      "You'll lose access to this workspace. The last owner cannot leave.",
    leaving: "Leaving…",
    leaveConfirm: "Leave this organization?",
    deleteOrg: "Delete organization",
    deleteOrgHint:
      "Permanently deletes projects, boards, cards, and members. This cannot be undone. Type the organization name to confirm.",
    deleting: "Deleting…",
    inviteEmailFailed:
      "Invitation created, but the email didn't send — you can share the link directly:",
    inviteEmailSent:
      "Email sent. The link is valid for 7 days — share it manually if needed:",
    expires: "expires",
    memberCount: "Members:",
    role: "Role",
  },
  billing: {
    title: "Billing",
    subtitle: "Plan and subscription for this organization",
    currentPlan: "Current plan",
    status: "Status",
    upgrade: "Upgrade to PRO",
    manage: "Manage billing",
    redirecting: "Redirecting…",
    ownerOnly: "Only the organization owner can manage billing.",
    success: "Subscription updated. Status may take a few seconds to appear.",
    canceled: "Checkout canceled. Your plan was not changed.",
    freeCap: "Free plan: up to",
    membersWord: "members.",
    unlimited: "Unlimited members.",
    upgradePrompt:
      "Free plan limit reached. Upgrade to PRO to continue.",
  },
  account: {
    title: "Account",
    subtitle: "Change your SYZX account password",
    password: "Password",
    passwordHint: "Other sessions end when you change your password.",
    current: "Current password",
    next: "New password",
    confirm: "Confirm new password",
    update: "Update password",
    updated: "Password updated.",
    confirmRequired: "Confirm your new password",
    confirmMismatch: "Passwords do not match",
  },
  comments: {
    title: "Comments",
    placeholder: "Write a comment…",
    send: "Send",
    sending: "Sending…",
    empty: "No comments yet",
    deleted: "Comment deleted",
    you: "You",
    loading: "Loading comments…",
    emptyHint: "Start a discussion on this card.",
    add: "Write a comment",
    member: "Member",
  },
  attachments: {
    title: "Attachments",
    empty: "No files attached.",
    loading: "Loading attachments…",
    drop: "Drop a file here or click to choose",
    uploading: "Uploading…",
    region: "Attachments",
    tooLarge: "File exceeds the maximum size",
    mbUnit: "MB",
    typeNotAllowed:
      "This file type is not allowed. Use images, PDF, text, or Office documents.",
    uploadFailed: "Couldn't upload the file. Check the size and try again.",
    uploadFailedNet:
      "Couldn't upload the file. Check your connection and try again.",
    mockDownload: "Download is unavailable in mock storage mode.",
    dropAria: "Drop a file or press Enter to choose",
    remove: "Remove",
  },
  notifications: {
    title: "Notifications",
    markAll: "Mark all read",
    empty: "All caught up",
    emptyHint: "New notifications will appear here.",
    loading: "Loading…",
    aria: "Notifications",
    unread: "unread",
  },
  invite: {
    title: "Invitation",
    notFound: "Invitation not found",
    home: "Go home",
    used: "Invitation already used",
    usedHint: "This link has already been accepted.",
    expired: "Invitation expired",
    expiredHint: "Ask an admin to send a new invitation.",
    join: "Join organization",
    accept: "Accept invitation",
    accepting: "Accepting…",
    invitedTo: "You've been invited to",
    as: "as",
    sentTo: "Invitation sent to",
    signInToAccept:
      "Sign in or register with the invited address to accept.",
    emailMustMatch:
      "Your account email must match the address on the invitation.",
  },
  theme: {
    toggle: "Toggle theme",
    light: "Light theme",
    dark: "Dark theme",
  },
  errors: {
    dashboard: "Dashboard error",
    dashboardHint: "An unexpected error occurred. Please try again.",
    board: "Error on this board",
    boardHint:
      "This board failed to load. The rest of your work is unaffected — try again.",
    accessDenied: "Access denied",
  },
  roles: {
    OWNER: "Owner",
    ADMIN: "Admin",
    MEMBER: "Member",
    VIEWER: "Viewer",
  } satisfies Record<Role, string>,
  priorities: {
    LOW: "Low",
    MEDIUM: "Medium",
    HIGH: "High",
    URGENT: "Urgent",
  } satisfies Record<Priority, string>,
} as const;

export function roleLabel(role: string): string {
  return copy.roles[role as Role] ?? role;
}

export function priorityLabel(priority: string): string {
  return copy.priorities[priority as Priority] ?? priority;
}
